### ISSUE TITLE
When visiting Reports for the 1st time nothing shows - need to reload

### ISSUE THREAD

**Issue by marsrobertson** [basexhq/front-end#1]
You can try a simple workaround `setTimeout( () => blah() )` to trigger update?

https://github.com/basexhq/front-end/assets/44369284/069bb631-0988-465d-982a-4fc7a6d85a21

**Comment by GregTrifan** [comment]
As I recall this was fixed a couple of weeks ago

**Comment by marsrobertson** [comment]
Thank you for fixing ser
