### ISSUE TITLE
Use EBF (ecological benefits framework) rather than SDG

### ISSUE THREAD

**Issue by marsrobertson** [basexhq/front-end#22]
Previously we were thinking about fields in #20 

But there is a better way: https://twitter.com/basexHQ/status/1728753963896607151

<img width="584" alt="image" src="https://github.com/basexhq/front-end/assets/44369284/accd0ae4-0f53-4c4e-ad42-389a78c8f409">

- Carbon: https://www.thelexicon.org/wp-content/uploads/2021/08/CO2.svg
- Air: https://www.thelexicon.org/wp-content/uploads/2021/08/WIND-HessaSulaiman.svg
- Water: https://www.thelexicon.org/wp-content/uploads/2021/08/WATERDROP.svg
- Soil: https://www.thelexicon.org/wp-content/uploads/2021/08/SOIL.svg
- Biodiversity: https://www.thelexicon.org/wp-content/uploads/2021/08/BIODIVERSITY-SarahStern.svg
- Equity: https://www.thelexicon.org/wp-content/uploads/2021/10/FAIRWAGESFORFARMERS-VeekshaMehndiratta.svg

_(linking to the SVG icons)_

<img width="517" alt="image" src="https://github.com/basexhq/front-end/assets/44369284/5d35a658-e01d-4faa-bf19-c054e9cae761">

**Comment by GregTrifan** [comment]
pushed on your fork a UI fixup, should cover for now till we get more in depth with that topic
