### ISSUE TITLE
Add missing fields on Report + make them required

### ISSUE THREAD

**Issue by marsrobertson** [basexhq/front-end#3]
<img width="1566" alt="image" src="https://github.com/basexhq/front-end/assets/44369284/d64a2e07-7a2d-441b-8bdf-fcfc7c52dfc4">

**Comment by marsrobertson** [comment]
Hey hey @GregTrifan this is super important, an organisation can add report for different dates.

**Comment by GregTrifan** [comment]
Pushed something regarding this issue https://github.com/marsrobertson/basex-front-end-fork-vercel/commit/d6e1cec600f3489ef8aedb7b31a4d5d8c58602aa
